In [2]:
# pip list 설치된 모듈 리스트 확인
# pandas의 기본 객체 series, DataFrame
# series : 1차원(하나의 row or col)
# DataFrame : 2차원(여러개의 row or col)
# key(row), index(col), value

In [2]:
import pandas as pd

s = pd.Series([1,2,3,4,5])
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e']) # index 변경
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [3]:
import numpy as np

a = np.array([1,2,3])
print(a)

# 0으로 채워진 array 만들기
b = np.zeros(3,dtype=int)
print(b)

# 1로 채워진 array 만들기
c = np.ones((2,3))
print(c)

# 두개의 array의 값들을 요소별로 더함
sum = np.add(a,b)
print(sum)

# 두개의 array의 값들을 요소별로 곱해줌
r = np.multiply(a,b)
print(r)

# array의 값들의 평균을 계산
avg = np.mean(a)
print(avg)

# random 0~1 범위 내에서 균일한 분포를 갖는 숫자 샘플링
rd = np.random.rand(2,3)
print(rd)
# 표준정규분포를 갖는 숫자 샘플링
rdn = np.random.randn(2,3)
print(rdn)

# 원주율
pi = np.pi
print(pi)

# 오일러상수
e = np.e
print(e)

# 2차원배열
ss = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ss)

[1 2 3]
[0 0 0]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]
[0 0 0]
2.0
[[0.65391326 0.00785419 0.15463362]
 [0.11598295 0.07352452 0.78854513]]
[[ 0.93440592 -0.75200277  0.43858887]
 [ 0.81670596  0.22672128 -0.47818072]]
3.141592653589793
2.718281828459045
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# pandas, numpy 사용
no = [1,2,3]
sjname = ['국어','영어','수학']
# no.append(1)
# no.append(2)

# pandas DataFrame 생성
subject = pd.DataFrame()
subject['과목번호'] = no
subject['과목명'] = sjname
print(subject)

subject.to_excel("C:\subject.xls", index=False)
subject.to_csv("C:\subject.csv", encoding='utf-8-sig',index=False)

   과목번호 과목명
0     1  국어
1     2  영어
2     3  수학


C:\Users\Administrator\AppData\Local\Temp\ipykernel_7728\2998041949.py:13: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  subject.to_excel("C:\subject.xls", index=False)


In [11]:
# 데이터 프레임은 파이썬의 리스트와 딕셔너리의 조합
df = pd.DataFrame({"이름":["홍길동","홍길순","임꺽정"],"나이":[22,25,30],"성별":["male","female","male"]})

# 전체 구조 출력
print(df)

# 데이터 프레임에서 이름 컬럼만 출력
print(df["이름"],df["성별"],sep="\n")

ages = pd.Series([22,35,50], name = "Age")
print(ages)

homes = pd.Series(['서울','대전','전주'],name = "고향")
df["고향"] = homes
print(df)

    이름  나이      성별
0  홍길동  22    male
1  홍길순  25  female
2  임꺽정  30    male
0    홍길동
1    홍길순
2    임꺽정
Name: 이름, dtype: object
0      male
1    female
2      male
Name: 성별, dtype: object
0    22
1    35
2    50
Name: Age, dtype: int64
    이름  나이      성별  고향
0  홍길동  22    male  서울
1  홍길순  25  female  대전
2  임꺽정  30    male  전주


In [19]:
# 집계 함수(평균,최대,최소 등)
print("최대 나이:",df["나이"].max())
print("최소 나이:",df["나이"].min())
print("평균 나이:",df["나이"].mean())

# 기본 통계 작성
print(df.describe())
# 첫번째부터 n번째까지
print(df.head(2))
# 마지막부터 n번째까지
print(df.tail(2))

최대 나이: 30
최소 나이: 22
평균 나이: 25.666666666666668
              나이
count   3.000000
mean   25.666667
std     4.041452
min    22.000000
25%    23.500000
50%    25.000000
75%    27.500000
max    30.000000
    이름  나이      성별  고향
0  홍길동  22    male  서울
1  홍길순  25  female  대전
    이름  나이      성별  고향
1  홍길순  25  female  대전
2  임꺽정  30    male  전주


In [58]:
df = pd.read_excel("order.xlsx")

# 1. 손흥민의 주문 개수는?
c1 = df["name"] == '손흥민'
order_count = df[c1]["name"].count()
print("손흥민 %d건의 주문이 있습니다." % order_count)
# 2. 손흥민이 산 상품은? 
print("손흥민 주문 상품 : ",df[c1]["product"].values)
# 3. 스커트를 산 사람은? 
c2 = df["product"] == '스커트'
print("스커트 주문자 :",df[c2]["name"].values)
# 4. 가장 많이 주문한 사람의 아이디와 이름, 주문개수는? 
# print(df.groupby(["user_id","name"])["order_no"].count())
ndf = df.groupby(["user_id","name"])["order_no"].count().reset_index(name = "count")
ndf = ndf.sort_values("count", ascending = False)
print("최대 주문자 user id :",ndf.loc[0][0],", name:",ndf.loc[0][1])
# 5. 김지원이 사용한 총 금액은? 
c4 = df["name"] == '김지원'
print("김지원 총 사용 금액 : ",df[c4]["price"].sum())

손흥민 3건의 주문이 있습니다.
손흥민 주문 상품 :  ['운동화' '스커트' '코트']
스커트 주문자 : ['송혜교' '손흥민']
최대 주문자 user id : user1 , name: 손흥민
김지원 총 사용 금액 :  229900
