In [2]:
# pip list 설치된 모듈 리스트 확인
# pandas의 기본 객체 series, DataFrame
# series : 1차원(하나의 row or col)
# DataFrame : 2차원(여러개의 row or col)
# key(row), index(col), value

In [2]:
import pandas as pd

s = pd.Series([1,2,3,4,5])
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e']) # index 변경
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [3]:
import numpy as np

a = np.array([1,2,3])
print(a)

# 0으로 채워진 array 만들기
b = np.zeros(3,dtype=int)
print(b)

# 1로 채워진 array 만들기
c = np.ones((2,3))
print(c)

# 두개의 array의 값들을 요소별로 더함
sum = np.add(a,b)
print(sum)

# 두개의 array의 값들을 요소별로 곱해줌
r = np.multiply(a,b)
print(r)

# array의 값들의 평균을 계산
avg = np.mean(a)
print(avg)

# random 0~1 범위 내에서 균일한 분포를 갖는 숫자 샘플링
rd = np.random.rand(2,3)
print(rd)
# 표준정규분포를 갖는 숫자 샘플링
rdn = np.random.randn(2,3)
print(rdn)

# 원주율
pi = np.pi
print(pi)

# 오일러상수
e = np.e
print(e)

# 2차원배열
ss = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ss)

[1 2 3]
[0 0 0]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]
[0 0 0]
2.0
[[0.73226899 0.14290965 0.87384487]
 [0.53250887 0.04069842 0.35185174]]
[[ 0.98275192 -1.85369446  0.14752993]
 [ 0.26119893 -0.27303006 -2.61783187]]
3.141592653589793
2.718281828459045
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# pandas, numpy 사용
no = [1,2,3]
sjname = ['국어','영어','수학']
# no.append(1)
# no.append(2)

# pandas DataFrame 생성
subject = pd.DataFrame()
subject['과목번호'] = no
subject['과목명'] = sjname
print(subject)

subject.to_excel("C:\subject.xls", index=False)
subject.to_csv("C:\subject.csv", encoding='utf-8-sig',index=False)

   과목번호 과목명
0     1  국어
1     2  영어
2     3  수학


C:\Users\Administrator\AppData\Local\Temp\ipykernel_7728\2998041949.py:13: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  subject.to_excel("C:\subject.xls", index=False)
